[workspace]
resolver = "2"
members = [
    "support/insn_def",
    "tools/gen_insn_dec"
]

[workspace.dependencies]
insn_def = { path = "support/insn_def" }

anyhow = "1"
bitflags = { version = "2.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
clap-num = "1"
log = "0.4"
env_logger = "0.11"
proc-macro2 = { version = "1", default-features = false }
quote = { version = "1", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.26"
strum_macros = "0.26"
