[package]
name = "insn_def"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
bitflags.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true