[package]
name = "disarm64"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bitfield-struct.workspace = true
clap.workspace = true
clap-num.workspace = true
log.workspace = true
env_logger.workspace = true
